name: portfolio_site_landing_staging

services:
  portfolio_site_landing:
    container_name: portfolio_site_landing_staging
    restart: "always"
    networks:
      - global_portfolio_site_network_staging

  portfolio_site_landing_nginx:
    container_name: portfolio_site_landing_nginx_staging
    restart: "always"
    ports:
      - "3100:80"
    volumes:
      - ./docker/nginx/default.staging.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - global_portfolio_site_network_staging

networks:
  global_portfolio_site_network_staging:
    external: true
